### PR TITLE
New Folder structure that matches webpack template and node server

### PR DESCRIPTION
**Pull request by vijaythecoder**

### CODE REVIEW

**Comment by Modelizer** [comment]
You did a really good work @vijaythecoder !

This PR has shape Laravue to has it's own unique position.

@amranidev do check this out and feel free what more enhancement or good we can bring to this project.

@vijaythecoder feel free to share ideas. Also, I do see we added complexity which we need to hide under the hood and make easier for a user to get started quickly and not messing up when a new version is available.

Will plan to version it soon when we are done with minimal doc and theme work.

**Comment by vijaythecoder** [comment]
The simple thing in this is , they need to worry only `src` directory and nothing else for developing their own SPA. if they decide to goto production, all they need is `npm run build` and that compiles the files to `dist` folder. which can be deployed over `HTTP`

**Comment by Modelizer** [comment]
Yeah, but what if we made some changes in `src`? I think that would end up in a conflict which we should keep it as minimum as possible.

**Comment by amranidev** [comment]
Totally agree with @Modelizer 

1. We should keep Laravel-elexir because it's easy and so familiar to Laravel developers to start compiling (sass,less, . . etc) , also they could put this repo to wherever they want in their laravel app.

2. I think that this project aims to make Laravel-developers develop SPA easily with out making change core Lib.

So all they have to do is write their Components.vue and define their (api configuration, routes).

**Comment by Modelizer** [comment]
Yeah!
I feel the same that's the reason I kept the name as `Laravue`.

Regarding elixir, I do use it but I'm quite confused right now. 

When it comes to SPA and we start adding load to it. I found the file which is compiled for ES6 example `app.js` has the size of 2 to 3 MB. Which is bit annoying when it goes to production. 

@amranidev can you please confirm on this issue?

Also, I do feel we can give developers more feature-enrich SPA by pushing current webpack configuration into elixir?

**Comment by vijaythecoder** [comment]
ok I am pretty sure you did not check the size of the production `app.js` right? @Modelizer , because when it comes to production it has only `15 KB` 
image

**Comment by vijaythecoder** [comment]
Also what I proposed is completely supported by Vuejs and they recommend this structure and also it can be easily integrated with Laravel which I am doing in some of my applications.

**Comment by Modelizer** [comment]
@vijaythecoder Regarding file size I was talking about elixir. 😅 

In our current configuration, I checked the file size and I saw it was 15KB. Impressive 👍

**Comment by amranidev** [comment]
@Modelizer , @vijaythecoder 
Given the same result even when using elixir or not.

- Development mode : ~3 MB
- Production mode : ~15 KB

**Comment by Modelizer** [comment]
Okay, give me some time I'll cross check it with my current SPA project which is built on top of elixir.

**Comment by Modelizer** [comment]
Okay, My bad. Result is same as what @amranidev gave except on production it's around ~500 KB

@vijaythecoder So can we make our current environment use elixir? I just wanted to hide or eliminate those stuff which elixir can handle. This way will get more functionality control as well Laravel people can get started more quickly.

Also, on a side note, I started working on [Lumenite](https://github.com/Qafeen/Lumenite) which will take control of API.

**Comment by Modelizer** [comment]
It would be awesome if we made Elixir compatible with listed below points which we have currently in our system.

1. Minified version of `index.html` file.
2. Automatically attaching CSS and JS to index file.
3. A separate command to start the server or hot reloading.
4. And much more (New ideas are welcome).

**Pull request merged**
